@extends('layouts.admin')
@section('title', 'Resumen')
@section('heading', 'Buenos días.')
@section('content')
<section class="stat-grid"><article><span>Productos</span><strong>{{ $productCount }}</strong><small>{{ $activeProductCount }} publicados</small></article><article><span>Clientes</span><strong>{{ $customerCount }}</strong><small>Registrados</small></article><article><span>Pedidos</span><strong>{{ $orderCount }}</strong><small>Total</small></article></section>
<section class="stat-grid admin-health"><article><span>Medios</span><strong>{{ $mediaCount }}</strong><small>{{ $mediaStorageMb }} MB almacenados</small></article><article><span>Productos con bajo stock</span><strong>{{ $lowStockProducts->count() }}</strong><small>≤ 10 unidades</small></article></section>
@if($draftChanges)<div class="notice warning"><strong>Hay cambios sin publicar en la página de inicio.</strong> <a href="{{ route('admin.homepage.edit') }}">Revisar borrador</a></div>@endif
<section class="admin-panel"><div class="panel-heading"><div><p class="eyebrow">Inventario</p><h2>Productos con pocas existencias</h2></div><a class="button button-small" href="{{ route('admin.products.create') }}">Nuevo producto</a></div><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Existencias</th><th>Estado</th></tr></thead><tbody>@forelse($lowStockProducts as $product)<tr><td data-label="Producto"><a href="{{ route('admin.products.edit', $product) }}">{{ $product->name }}</a><small>{{ $product->sku }}</small></td><td data-label="Existencias">{{ $product->stock }}</td><td data-label="Estado"><span class="status {{ $product->stock === 0 ? 'danger' : 'warning' }}">{{ $product->stock === 0 ? 'Agotado' : 'Bajo' }}</span></td></tr>@empty<tr><td class="table-empty" colspan="3">Todos los productos tienen existencias suficientes.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-panel dashboard-activity"><div class="panel-heading"><div><p class="eyebrow">Ventas</p><h2>Pedidos recientes</h2></div><a class="button button-small" href="{{ route('admin.orders.index') }}">Ver todos</a></div>@forelse($recentOrders as $order)<div class="activity-summary"><span>{{ $order->created_at->diffForHumans() }}</span><p><strong>{{ $order->number }}</strong> — {{ $order->customer_name }} — ${{ number_format($order->total, 2) }}</p></div>@empty<p>Aún no hay pedidos.</p>@endforelse</section>
@endsection
