@extends('layouts.admin')
@section('title', 'Resumen')
@section('heading', 'Buenos días.')
@section('content')
<section class="stat-grid"><article><span>Productos totales</span><strong>{{ $productCount }}</strong><small>En todo el catálogo</small></article><article><span>Productos visibles</span><strong>{{ $activeProductCount }}</strong><small>Publicados en la tienda</small></article><article><span>Categorías</span><strong>{{ $categoryCount }}</strong><small>Colecciones de productos</small></article></section>
<section class="stat-grid admin-health"><article><span>Medios</span><strong>{{ $mediaCount }}</strong><small>{{ $mediaStorageMb }} MB almacenados</small></article><article><span>Productos incompletos</span><strong>{{ $incompleteProductCount }}</strong><small>Sin imagen, EAN o SEO</small></article><article><span>Listos para canales</span><strong>{{ $marketplaceReadyCount }}</strong><small>Con datos logísticos básicos</small></article></section>
@if($draftChanges)<div class="notice warning"><strong>Hay cambios sin publicar en la página de inicio.</strong> <a href="{{ route('admin.homepage.edit') }}">Revisar borrador</a></div>@endif
<section class="admin-panel"><div class="panel-heading"><div><p class="eyebrow">Atención de inventario</p><h2>Productos con pocas existencias</h2></div><a class="button button-small" href="{{ route('admin.products.create') }}">Agregar producto</a></div><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Existencias</th><th>Estado</th></tr></thead><tbody>@forelse($lowStockProducts as $product)<tr><td data-label="Producto"><a href="{{ route('admin.products.edit', $product) }}">{{ $product->name }}</a><small>{{ $product->sku }}</small></td><td data-label="Categoría">{{ $product->category->name }}</td><td data-label="Existencias">{{ $product->stock }}</td><td data-label="Estado"><span class="status {{ $product->stock === 0 ? 'danger' : 'warning' }}">{{ $product->stock === 0 ? 'Agotado' : 'Bajo' }}</span></td></tr>@empty<tr><td class="table-empty" colspan="4">Todos los productos tienen existencias suficientes.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-panel dashboard-activity"><div class="panel-heading"><div><p class="eyebrow">Cambios recientes</p><h2>Actividad del equipo</h2></div><a class="button button-small" href="{{ route('admin.activity.index') }}">Ver historial</a></div>@forelse($recentActivities as $activity)<div class="activity-summary"><span>{{ $activity->created_at->diffForHumans() }}</span><p><strong>{{ $activity->user?->name ?? 'Sistema' }}</strong> {{ $activity->description }}</p></div>@empty<p>Aún no hay actividad registrada.</p>@endforelse</section>
@endsection
