@extends('layouts.admin')
@section('title', 'Configuración') @section('heading', 'Configuración del sitio')
@section('content')
<form class="admin-form" method="POST" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Identidad</p><h2>Marca y contacto</h2></div></div><div class="form-grid"><label>Nombre de marca<input name="brand_name" value="{{ old('brand_name',$settings['brand_name']) }}" required></label><label>Lema<input name="tagline" value="{{ old('tagline',$settings['tagline']) }}" required></label><label class="span-2">Aviso superior<input name="announcement" value="{{ old('announcement',$settings['announcement']) }}" maxlength="240"></label><label>Correo<input type="email" name="email" value="{{ old('email',$settings['email']) }}" required></label><label>Teléfono<input name="phone" value="{{ old('phone',$settings['phone']) }}"></label><label>Instagram<input type="url" name="instagram" value="{{ old('instagram',$settings['instagram']) }}"></label><label>Facebook<input type="url" name="facebook" value="{{ old('facebook',$settings['facebook']) }}"></label></div></section>
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Buscadores</p><h2>SEO predeterminado</h2></div></div><div class="form-grid"><label class="span-2">Título SEO<input name="seo_title" maxlength="70" value="{{ old('seo_title',$settings['seo_title']) }}" required></label><label class="span-2">Descripción SEO<textarea name="seo_description" maxlength="160" rows="3" required>{{ old('seo_description',$settings['seo_description']) }}</textarea></label></div></section>
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Comercio</p><h2>Configuración de envío</h2></div></div><div class="form-grid"><label>Costo de envío estándar (MXN)<input type="number" step="0.01" min="0" name="standard_shipping_cost" value="{{ old('standard_shipping_cost',$settings['standard_shipping_cost']) }}" required></label></div></section>
<div class="form-actions"><button class="button button-dark" type="submit">Guardar configuración</button></div></form>
@endsection
