@extends('layouts.admin')
@section('title', $product->exists ? 'Edit product' : 'New product')
@section('heading', $product->exists ? 'Edit product' : 'New product')
@section('content')
<form class="admin-form" method="POST" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Product story</p><h2>Essential information</h2></div></div><div class="form-grid"><label class="span-2">Product name<input name="name" value="{{ old('name', $product->name) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $product->slug) }}" placeholder="Generated from name"></label><label>SKU<input name="sku" value="{{ old('sku', $product->sku) }}" required></label><label>Category<select name="category_id" required><option value="">Choose a category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Size label<input name="size_label" value="{{ old('size_label', $product->size_label) }}" placeholder="50 ml"></label><label class="span-2">Short description<textarea name="short_description" rows="2" maxlength="240" required>{{ old('short_description', $product->short_description) }}</textarea></label><label class="span-2">Full description<textarea name="description" rows="7">{{ old('description', $product->description) }}</textarea></label></div></section>
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Commerce</p><h2>Price and availability</h2></div></div><div class="form-grid"><label>Price (MXN)<input type="number" step="0.01" min="0" name="price" value="{{ old('price', $product->price) }}" required></label><label>Compare-at price<input type="number" step="0.01" min="0" name="compare_at_price" value="{{ old('compare_at_price', $product->compare_at_price) }}"></label><label>Stock<input type="number" min="0" name="stock" value="{{ old('stock', $product->stock ?? 0) }}" required></label><label>Image URL<input type="url" name="image_url" value="{{ old('image_url', $product->image_url) }}" placeholder="Images will be uploaded later"></label><label class="check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->exists ? $product->is_active : true))> Published</label><label class="check"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $product->is_featured))> Feature on homepage</label></div></section>
<div class="form-actions"><a href="{{ route('admin.products.index') }}">Cancel</a><button class="button button-dark" type="submit">{{ $product->exists ? 'Save changes' : 'Create product' }}</button></div></form>
@endsection
