@extends('layouts.admin')
@section('title', $product->exists ? 'Editar producto' : 'Nuevo producto')
@section('heading', $product->exists ? 'Editar producto' : 'Nuevo producto')
@section('content')
<form class="admin-form" method="POST" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Historia del producto</p><h2>Información esencial</h2></div></div><div class="form-grid"><label class="span-2">Nombre del producto<input name="name" value="{{ old('name', $product->name) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $product->slug) }}" placeholder="Se genera a partir del nombre"></label><label>SKU<input name="sku" value="{{ old('sku', $product->sku) }}" required></label><label>Categoría<select name="category_id" required><option value="">Selecciona una categoría</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Presentación<input name="size_label" value="{{ old('size_label', $product->size_label) }}" placeholder="50 ml"></label><label class="span-2">Descripción breve<textarea name="short_description" rows="2" maxlength="240" required>{{ old('short_description', $product->short_description) }}</textarea></label><label class="span-2">Descripción completa<textarea name="description" rows="7">{{ old('description', $product->description) }}</textarea></label></div></section>
<section class="form-panel"><div class="panel-heading"><div><p class="eyebrow">Comercio</p><h2>Precio y disponibilidad</h2></div></div><div class="form-grid"><label>Precio (MXN)<input type="number" step="0.01" min="0" name="price" value="{{ old('price', $product->price) }}" required></label><label>Precio anterior<input type="number" step="0.01" min="0" name="compare_at_price" value="{{ old('compare_at_price', $product->compare_at_price) }}"></label><label>Existencias<input type="number" min="0" name="stock" value="{{ old('stock', $product->stock ?? 0) }}" required></label><label>URL de imagen<input type="url" name="image_url" value="{{ old('image_url', $product->image_url) }}" placeholder="Las imágenes se subirán después"></label><label class="check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->exists ? $product->is_active : true))> Publicado</label><label class="check"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $product->is_featured))> Destacar en la página principal</label></div></section>
<div class="form-actions"><a href="{{ route('admin.products.index') }}">Cancelar</a><button class="button button-dark" type="submit">{{ $product->exists ? 'Guardar cambios' : 'Crear producto' }}</button></div></form>
@endsection
